### PR TITLE
ParentChanges

### PR DESCRIPTION
**Pull request by ormaq**
Make sure that parent is of type 'string'

And make sure our page has a main element before attaching. if not use body element

### CODE REVIEW

**Comment by GoToLoop** [comment]
This library q5#js is more about minimalism, and in general, it doesn't aggressively check if we are passing an argument of the expected datatype.

BtW, if method **parent()** is supposed to match p5*js, it needs to accept other datatypes too:
https://p5js.org/reference/#/p5.Element/parent

**Comment by ormaq** [comment]
Updated it to include all parent options

**Comment by GoToLoop** [comment]
`try {} catch () {}` blocks aren't the best way to check for arguments datatype.
Take a look at how p5*js implements that for method **parent()**:
https://github.com/processing/p5.js/blob/v1.7.0/src/core/p5.Element.js#L110-L125

**Comment by quinton-ashley** [comment]
Not going to merge this PR cause the idea of q5 is it doesn't do any warnings. `parent` can accept a string or a DOM element.

But you did make me think about which is faster to run, using `typeof` or my hacky version checking for a string by checking if it has a character `el[0]`. Turns out `typeof` is faster and of course more readable, so I changed it.

Also I changed all instances of `appendChild` to `append`.

**Pull request closed without merging**
